### ISSUE TITLE
AssertionError  When num_topic=1 gensim

### ISSUE THREAD

**Issue by raviolli** [bmabey/pyLDAvis#118]
I recieved the error below when I set the `num_topic=1` when training my LDA model in gensim. If I set `num_topic=2` `gensim.prepare()` works fine.

```
Traceback (most recent call last):
  File "topic_extraction.py", line 170, in <module>
    ret = pyLDAvis.gensim.prepare(model, corpus, dictionary)
  File "/usr/local/lib/python2.7/dist-packages/pyLDAvis/gensim.py", line 119, in prepare
    return vis_prepare(**opts)
  File "/usr/local/lib/python2.7/dist-packages/pyLDAvis/_prepare.py", line 400, in prepare
    topic_coordinates = _topic_coordinates(mds, topic_term_dists, topic_proportion)
  File "/usr/local/lib/python2.7/dist-packages/pyLDAvis/_prepare.py", line 184, in _topic_coordinates
    assert mds_res.shape == (K, 2)
AssertionError
```

**Comment by raviolli** [comment]
Having a single topic screws up the calculations of Distinctiveness due log of 1 == 0.

**Comment by hugomailhot** [comment]
Why would you want to train a topic model with only one topic?

**Comment by chinnichaitanya** [comment]
@hugomailhot: Coherence score might suggest that the number of topics is only one. It could be for research purposes.
