### ISSUE TITLE
AssertionError on running pyLDAVis on Windows and Anaconda distribution

### ISSUE THREAD

**Issue by napsternxg** [bmabey/pyLDAvis#20]
System Windows 10
Python Distribution Anaconda
Installed latest pyLDAVis
I am running the following code and am getting error
```python
%matplotlib inline
import matplotlib.pyplot as plt
import seaborn as sns
import pandas as pd

import gensim
import pyLDAvis
pyLDAvis.enable_notebook()

dictionary = gensim.corpora.Dictionary.load('ID2Word.dict')
corpus = gensim.corpora.MmCorpus('BOWCORPUS.mm')
lda = gensim.models.ldamodel.LdaModel.load('LDAModel_BOW.model')

import pyLDAvis.gensim

pyLDAvis.gensim.prepare(lda, corpus, dictionary)
```

On running the last line of my code the execution never finishes and I keep getting continuous error messages like the following:
```
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 380, in main
Traceback (most recent call last):
  File "<string>", line 1, in <module>
    prepare(preparation_data)
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 380, in main
        prepare(preparation_data)
assert main_name not in sys.modules, main_name
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
AssertionError: __main__
    assert main_name not in sys.modules, main_name
AssertionError: __main__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "E:\Anaconda\lib\multiprocessing\forking.py", line 488, in prepare
    assert main_name not in sys.modules, main_name
AssertionError: __main__
```

**Comment by bmabey** [comment]
The problem appears to be with the multiprocessing part. So, probably the best way around that is to only use a single core. To do that pass `n_jobs=1` to the `prepare` function.

Also, I just released version `1.3.0` that has some fixes for the gensim code so you should upgrade to that since it looks like you are using gensim.
