### ISSUE TITLE
Error when installing pyldavis

### ISSUE THREAD

**Issue by StamatisTiniakos** [bmabey/pyLDAvis#207]
I get errors when installing pyLDAvis on windows. I uninstalled enum34 as suggested in some other posts over the web but the problem persist. Any ideas what I am doing wrong?

`PS C:\WINDOWS\system32> py -m pip install pyLDAvis --user
Collecting pyLDAvis
  Using cached pyLDAvis-3.3.1.tar.gz (1.7 MB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\Python\python.exe' 'C:\Python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\P10494483\AppData\Local\Temp\pip-build-env-r3yrzqdw\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools
       cwd: None
  Complete output (31 lines):
  Traceback (most recent call last):
    File "C:\Python\lib\runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "C:\Python\lib\runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "C:\Python\lib\site-packages\pip\__main__.py", line 26, in <module>
      sys.exit(_main())
    File "C:\Python\lib\site-packages\pip\_internal\cli\main.py", line 73, in main
      command = create_command(cmd_name, isolated=("--isolated" in cmd_args))
    File "C:\Python\lib\site-packages\pip\_internal\commands\__init__.py", line 104, in create_command
      module = importlib.import_module(module_path)
    File "C:\Python\lib\importlib\__init__.py", line 127, in import_module
      return _bootstrap._gcd_import(name[level:], package, level)
    File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
    File "<frozen importlib._bootstrap>", line 991, in _find_and_load
    File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
    File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
    File "<frozen importlib._bootstrap_external>", line 783, in exec_module
    File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
    File "C:\Python\lib\site-packages\pip\_internal\commands\install.py", line 17, in <module>
      from pip._internal.cli.req_command import RequirementCommand, with_cleanup
    File "C:\Python\lib\site-packages\pip\_internal\cli\req_command.py", line 22, in <module>
      from pip._internal.req.constructors import (
    File "C:\Python\lib\site-packages\pip\_internal\req\__init__.py", line 10, in <module>
      from .req_install import InstallRequirement
    File "C:\Python\lib\site-packages\pip\_internal\req\req_install.py", line 10, in <module>
      import uuid
    File "C:\Python\lib\site-packages\uuid.py", line 138
      if not 0 <= time_low < 1<<32L:
                                  ^
  SyntaxError: invalid syntax
  ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\Python\python.exe' 'C:\Python\lib\site-packages\pip' install --ignore-installed --no-user --prefix 'C:\Users\P10494483\AppData\Local\Temp\pip-build-env-r3yrzqdw\overlay' --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- setuptools Check the logs for full command output`

**Comment by bergen288** [comment]
I have the same error message on Windows 10 laptop.  Is there any fix/workaround?

Thanks.

**Comment by bergen288** [comment]
Strange.  The workaround is to ```pip uninstall uuid```.  At least it allows me to install pyldavis package now.

**Comment by laurarosenberg** [comment]
I have the same problem pip uninstall uuid doesn't work for me. Is there any other solution?

**Comment by bergen288** [comment]
@laurarosenberg 
In last 2 weeks, I installed Python/R packages via Anaconda on my Windows Server 2016.  I have no problem to install pyldavis with ```conda install -c conda-forge pyldavis```.

**Comment by tanyaapaul** [comment]
same error!

**Comment by msusol** [comment]
https://github.com/bmabey/pyLDAvis/pull/221 pulled into vs 3.4.0
