### ISSUE TITLE
Can't run notebook example

### ISSUE THREAD

**Issue by ariddell** [bmabey/pyLDAvis#8]
The library looks great. Thank you!

Just trying to run the notebook example with IPython 3.1.0 and hitting this error (including only the top):

```
---------------------------------------------------------------------------
RemoteTraceback                           Traceback (most recent call last)
RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/home/ag/.virtualenvs/py3/lib/python3.4/site-packages/joblib/parallel.py", line 92, in __call__
    return self.func(*args, **kwargs)
  File "/home/ag/.virtualenvs/py3/lib/python3.4/site-packages/pyLDAvis/_prepare.py", line 136, in _find_relevance_chunks
    return pd.concat(map(lambda l: _find_relevance(log_ttd, log_lift, R, l), lambda_seq))
  File "/usr/lib/python3/dist-packages/pandas/tools/merge.py", line 929, in concat
    verify_integrity=verify_integrity)
  File "/usr/lib/python3/dist-packages/pandas/tools/merge.py", line 944, in __init__
    '"{0}"'.format(type(objs).__name__))
AssertionError: first argument must be a list-like of pandas objects, you passed an object of type "map"

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.4/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/home/ag/.virtualenvs/py3/lib/python3.4/site-packages/joblib/parallel.py", line 102, in __call__
    raise TransportableException(text, e_type)
joblib.my_exceptions.TransportableException: TransportableException
```

**Comment by bmabey** [comment]
Hmm.. odd that the travis tests didn't detect this. What version of pandas are you using?

**Comment by ariddell** [comment]
0.13.1

**Comment by bmabey** [comment]
@ariddell okay, a newer version of pandas may help. For now though could you clone master of pyLDAVis and install it (`python setup.py install`) to see if my latest commit fixes it for 13?

**Comment by ariddell** [comment]
I'm not having much luck getting the newer IPython installed, so this is proving hard to test. I'll keep you posted if I figure it out.

**Comment by bmabey** [comment]
To test this fix I made you don't need any newer libraries aside from installing this one from master.

**Comment by ariddell** [comment]
Nothing's showing up in my old IPython notebook window although the error does disappear (there are just a lot of numpy warnings).

Sorry for the imprecise report. I can open a new issue if I have time to dig into this and reproduce it.

**Comment by ariddell** [comment]
Could there be a circular import somewhere? Now I'm getting this:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-9-f963778b0dc8> in <module>()
----> 1 import pyLDAvis

/home/ag/.virtualenvs/py3/lib/python3.4/site-packages/pyLDAvis-1.2.0-py3.4.egg/pyLDAvis/__init__.py in <module>()
     41 __version__ = '1.2.0'
     42 
---> 43 from ._display import *
     44 from ._prepare import prepare, js_PCoA, PreparedData

/home/ag/.virtualenvs/py3/lib/python3.4/site-packages/pyLDAvis-1.2.0-py3.4.egg/pyLDAvis/_display.py in <module>()
     12 from .utils import get_id, write_ipynb_local_js, NumPyEncoder
     13 from ._prepare import PreparedData
---> 14 from . import urls
     15 
     16 __all__ = ["prepared_data_to_html", "display",

ImportError: cannot import name 'urls'
```

**Comment by bmabey** [comment]
I have seen that problem in the past but it has happened when I reload the modules during development. I didn't think it would happen with clean/initial imports, at least I've never seen it happen in that case. I don't see a circular dep but I could be wrong. I'm not sure how else to explain the error since my python experience is limited.

**Comment by ariddell** [comment]
No worries. I'll get to the bottom of it eventually. Thanks for the project!
