### ISSUE TITLE
TypeError: (-0+0j) is not JSON serializable in save_html

### ISSUE THREAD

**Issue by hurcy** [bmabey/pyLDAvis#87]
Hi, while I save pyldavis as html,  TypeError is occurred.
It does not always happen. I think my ldamodel have unusual values.
Anyway how do I export html in such a case?

Traceback (most recent call last):
  File "/home/hcinyoung/dev/horai/lwtm/test/testlda.py", line 201, in test_multilda
    pyLDAvis.save_html(prepared_data, viz_name)
  File "/home/hcinyoung/anaconda3/envs/tm/lib/python2.7/site-packages/pyLDAvis/_display.py", line 362, in save_html
    fileobj.write(prepared_data_to_html(data, **kwargs))
  File "/home/hcinyoung/anaconda3/envs/tm/lib/python2.7/site-packages/pyLDAvis/_display.py", line 178, in prepared_data_to_html
    vis_json=data.to_json(),
  File "/home/hcinyoung/anaconda3/envs/tm/lib/python2.7/site-packages/pyLDAvis/_prepare.py", line 416, in to_json
    return json.dumps(self.to_dict(), cls=NumPyEncoder)
  File "/home/hcinyoung/anaconda3/envs/tm/lib/python2.7/json/__init__.py", line 251, in dumps
    sort_keys=sort_keys, **kw).encode(obj)
  File "/home/hcinyoung/anaconda3/envs/tm/lib/python2.7/json/encoder.py", line 207, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/home/hcinyoung/anaconda3/envs/tm/lib/python2.7/json/encoder.py", line 270, in iterencode
    return _iterencode(o, 0)
  File "/home/hcinyoung/anaconda3/envs/tm/lib/python2.7/site-packages/pyLDAvis/utils.py", line 146, in default
    return json.JSONEncoder.default(self, obj)
  File "/home/hcinyoung/anaconda3/envs/tm/lib/python2.7/json/encoder.py", line 184, in default
    raise TypeError(repr(o) + " is not JSON serializable")
TypeError: (-0+0j) is not JSON serializable

**Comment by monera23** [comment]
Hello.

Did you find any solution for this problem. I am also facing the same problem.

**Comment by hurcy** [comment]
I solved it using this issue. 
I'm not sure it is perfect solution, but I don't see the error anymore. 
https://github.com/bmabey/pyLDAvis/issues/69



2017. 3. 1. 오후 2:48 Shrikant Jituri <notifications@github.com> 작성:

**Comment by krageon** [comment]
It's very much an imperfect solution - I lack the domain knowledge to make an insightful dialogue out of it, but the long and short of it is that the fix mentioned in there is a crude hack (and probably misrepresents the complex number in the output by pulling it through ```abs```)
